### ISSUE TITLE
A bit confused

### ISSUE THREAD

**Issue by springcoil** [ColCarroll/flymc3#1]
`source ~/.venv/flymc3/bin/activate && ~/.venv/flymc3/bin/python setup.py develop
/bin/sh: /Users/peadarcoyle/.venv/flymc3/bin/activate: No such file or directory`

Have you encountered stuff like this more. Maybe something is wrong in my virtual environment set up.

**Comment by springcoil** [comment]
Figured it out had to create an environment first.

**Comment by ColCarroll** [comment]
Ah shoot -- that's left over from my personal [.bashrc](https://github.com/ColCarroll/dotfiles/blob/master/.bashrc#L29) which stashes virtual environments in `~/.venv/$PROJECT_NAME`. 

 I'll update the `README` and `Makefile` to be more universal, but a quick fix is to `mkdir -d ~/.venv && virtualenv ~/.venv/flymc3`.
